GO
CREATE DATABASE TIKUZO;
GO

use TIKUZO;

CREATE TABLE customer(
	customer_ID VARCHAR(12) PRIMARY KEY,
	nama VARCHAR(20),
	password VARCHAR(12),
	no_hp VARCHAR(15),
	email VARCHAR(30) UNIQUE
);

CREATE TABLE pesanan(
	pesanan_ID VARCHAR(12) PRIMARY KEY,
	customer_ID VARCHAR(12) NOT NULL,
	CONSTRAINT FK_pesanan FOREIGN KEY (customer_ID) REFERENCES customer(customer_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE pembayaran(
	pembayaran_ID VARCHAR(12) NOT NULL,
	status BIT NOT NULL,
	waktu_pembayaran TIMESTAMP,
	metode VARCHAR(10),
	pesanan_ID VARCHAR(12) NOT NULL,
	CONSTRAINT FK_pembayaran FOREIGN KEY (pesanan_ID) REFERENCES pesanan(pesanan_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT PK_pembayaran PRIMARY KEY (pembayaran_ID, status)
);

CREATE TABLE jadwal(
	jadwal_ID VARCHAR(12) PRIMARY KEY,
	tanggal DATE NOT NULL,
	jam_mulai TIME NOT NULL
);

CREATE TABLE tiket(
	tiket_ID VARCHAR(12) PRIMARY KEY,
	harga INT NOT NULL,
	jadwal_ID VARCHAR(12) NOT NULL,
	pesanan_ID VARCHAR(12) NOT NULL,
	CONSTRAINT FK_tiket1 FOREIGN KEY (jadwal_ID) REFERENCES jadwal(jadwal_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_tiket2 FOREIGN KEY (pesanan_ID) REFERENCES pesanan(pesanan_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE film(
	film_ID VARCHAR(12) PRIMARY KEY,
	durasi INT NOT NULL,
	genre VARCHAR(20) NOT NULL,
	judul VARCHAR(30) NOT NULL,
	sinopsis TEXT 
);

CREATE TABLE jadwal_film(
	film_ID VARCHAR(12) FOREIGN KEY REFERENCES film(film_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	jadwal_ID VARCHAR(12) FOREIGN KEY REFERENCES jadwal(jadwal_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE kota_provinsi(
	kota VARCHAR(20) PRIMARY KEY,
	provinsi VARCHAR(20) NOT NULL
);

CREATE TABLE bioskop(
	nama VARCHAR(25) PRIMARY KEY,
	brand VARCHAR(5) NOT NULL,
	jalan VARCHAR(50) NOT NULL,
	kota VARCHAR(20) FOREIGN KEY REFERENCES kota_provinsi(kota) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE studio(
	studio_ID VARCHAR(12) PRIMARY KEY,
	tipe varchar(15),
	nama VARCHAR(25) FOREIGN KEY REFERENCES bioskop(nama) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE jadwal_studio(
	studio_ID VARCHAR(12) FOREIGN KEY REFERENCES studio(studio_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	jadwal_ID VARCHAR(12) FOREIGN KEY REFERENCES jadwal(jadwal_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE kursi_studio(
	studio_ID VARCHAR(12) FOREIGN KEY REFERENCES studio(studio_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	no_kursi VARCHAR(4) NOT NULL,
	status BIT,
	CONSTRAINT PK_kursi_studio PRIMARY KEY (studio_ID, no_kursi)
);
